services:
  redis:
    image: redis:7-alpine
    container_name: exam_proctoring_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:16-alpine
    container_name: exam_proctoring_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exam_proctoring
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redisdata:
  pgdata:
