"""check

Revision ID: 15aed84e2a0f
Revises: e950e8e05fd5
Create Date: 2026-02-11 17:50:59.524382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15aed84e2a0f'
down_revision: Union[str, Sequence[str], None] = 'e950e8e05fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_device_fp', 'user_devices', ['fingerprint'], unique=False)
    op.create_index('idx_user_device_user', 'user_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_device_user', table_name='user_devices')
    op.drop_index('idx_user_device_fp', table_name='user_devices')
    # ### end Alembic commands ###
