"""add unlock_requests to users

Revision ID: 679af9f4c88f
Revises: 0badc7e60883
Create Date: 2026-02-10 18:05:32.101500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679af9f4c88f'
down_revision: Union[str, Sequence[str], None] = '0badc7e60883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column(
        "users",
        sa.Column("unlock_requests", sa.Integer(), nullable=True)
    )

    # 2. Backfill existing rows
    op.execute(
        "UPDATE users SET unlock_requests = 0 WHERE unlock_requests IS NULL"
    )

    # 3. Enforce NOT NULL
    op.alter_column(
        "users",
        "unlock_requests",
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unlock_requests')
    # ### end Alembic commands ###
