"""remove terminate_threshold

Revision ID: 815b15263e07
Revises: 0f7e91e17780
Create Date: 2026-03-10 22:29:14.570363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815b15263e07'
down_revision: Union[str, Sequence[str], None] = '0f7e91e17780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'terminate_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('terminate_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
