"""add security and consent fields to users

Revision ID: 97064ef6ea8b
Revises: 98ad322f874d
Create Date: 2026-02-10 13:53:01.172847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97064ef6ea8b'
down_revision: Union[str, Sequence[str], None] = '98ad322f874d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('consent_given', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('consent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('privacy_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_version')
    op.drop_column('users', 'consent_at')
    op.drop_column('users', 'consent_given')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
