"""add last_profile_image_update to users

Revision ID: 98ad322f874d
Revises: 3703a3d8e2bd
Create Date: 2026-02-06 17:17:37.243589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ad322f874d'
down_revision: Union[str, Sequence[str], None] = '3703a3d8e2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_profile_image_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_profile_image_update')
    # ### end Alembic commands ###
