"""add_dynamic_engine_settings_columns

Revision ID: a408ac074e9f
Revises: f2b3c4d5e6f7
Create Date: 2026-04-02 11:00:08.550908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a408ac074e9f'
down_revision: Union[str, Sequence[str], None] = 'f2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('engine_containers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('engine_containers', 'updated_at')
    T = sa.text
    # Detection toggles — default true
    for col in ('detect_looking_away','detect_looking_down','detect_looking_up','detect_looking_side',
                'detect_face_hidden','detect_partial_face','detect_fake_presence','detect_speaker_audio',
                'detect_phone','detect_book','detect_headphone','detect_earbud','detect_multiple_people'):
        op.add_column('engine_settings', sa.Column(col, sa.Boolean(), nullable=False, server_default=T('true')))
    # Float columns with their defaults
    float_defaults = {
        'partial_face_duration_gate': 5.0, 'face_hidden_dur_1': 5.0, 'face_hidden_dur_2': 10.0,
        'no_person_dur_1': 5.0, 'no_person_dur_2': 10.0,
        'fake_presence_dur_1': 10.0, 'fake_presence_dur_2': 25.0,
        'partial_face_score': 2.0, 'face_hidden_score_1': 10.0, 'face_hidden_score_2': 20.0,
        'speaker_warn_cooldown': 3.0, 'speaker_alert_cooldown': 10.0,
        'speaker_occ1_warn_s': 3.0, 'speaker_occ1_score': 10.0, 'speaker_occ1_repeat': 20.0,
        'speaker_occ2_warn_s': 5.0, 'speaker_occ2_score': 20.0, 'speaker_occ2_repeat': 20.0,
        'speaker_repeat_interval': 10.0,
        'score_cd_looking_away': 5.0, 'score_cd_looking_down': 5.0, 'score_cd_looking_up': 5.0,
        'score_cd_looking_side': 5.0, 'score_cd_partial_face': 5.0, 'score_cd_face_hidden': 5.0,
        'score_cd_fake_presence': 10.0, 'score_cd_phone': 15.0, 'score_cd_multiple_people': 10.0,
        'score_cd_no_person': 10.0, 'score_cd_book': 30.0, 'score_cd_headphone': 30.0,
        'score_cd_earbud': 30.0, 'score_cd_speaker_audio': 10.0,
        'warn_cd_looking_away': 3.0, 'warn_cd_looking_down': 3.0, 'warn_cd_looking_up': 3.0,
        'warn_cd_looking_side': 3.0, 'warn_cd_partial_face': 3.0, 'warn_cd_face_hidden': 3.0,
        'warn_cd_fake_presence': 5.0, 'warn_cd_phone': 8.0, 'warn_cd_multiple_people': 5.0,
        'warn_cd_no_person': 5.0, 'warn_cd_book': 15.0, 'warn_cd_headphone': 15.0,
        'warn_cd_earbud': 15.0, 'warn_cd_speaker_audio': 3.0,
        'face_hidden_recency_s': 4.0,
    }
    for col, default in float_defaults.items():
        op.add_column('engine_settings', sa.Column(col, sa.Float(), nullable=False, server_default=T(str(default))))
    # Integer columns
    op.add_column('engine_settings', sa.Column('min_face_width',  sa.Integer(), nullable=False, server_default=T('110')))
    op.add_column('engine_settings', sa.Column('min_face_height', sa.Integer(), nullable=False, server_default=T('120')))
    op.alter_column('engine_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('engine_settings', 'updated_at')
    op.alter_column('exam_engine_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('exam_engine_assignments', 'updated_at')
    op.create_index(op.f('ix_proctor_alerts_session_id'), 'proctor_alerts', ['session_id'], unique=False)
    op.drop_constraint(op.f('proctor_alerts_session_id_fkey'), 'proctor_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'proctor_alerts', 'exam_sessions', ['session_id'], ['id'])
    op.create_index(op.f('ix_proctor_warnings_session_id'), 'proctor_warnings', ['session_id'], unique=False)
    op.drop_constraint(op.f('proctor_warnings_session_id_fkey'), 'proctor_warnings', type_='foreignkey')
    op.create_foreign_key(None, 'proctor_warnings', 'exam_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proctor_warnings', type_='foreignkey')
    op.create_foreign_key(op.f('proctor_warnings_session_id_fkey'), 'proctor_warnings', 'exam_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_proctor_warnings_session_id'), table_name='proctor_warnings')
    op.drop_constraint(None, 'proctor_alerts', type_='foreignkey')
    op.create_foreign_key(op.f('proctor_alerts_session_id_fkey'), 'proctor_alerts', 'exam_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_proctor_alerts_session_id'), table_name='proctor_alerts')
    op.add_column('exam_engine_assignments', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('exam_engine_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('engine_settings', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('engine_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('engine_settings', 'face_hidden_recency_s')
    op.drop_column('engine_settings', 'min_face_height')
    op.drop_column('engine_settings', 'min_face_width')
    op.drop_column('engine_settings', 'warn_cd_speaker_audio')
    op.drop_column('engine_settings', 'warn_cd_earbud')
    op.drop_column('engine_settings', 'warn_cd_headphone')
    op.drop_column('engine_settings', 'warn_cd_book')
    op.drop_column('engine_settings', 'warn_cd_no_person')
    op.drop_column('engine_settings', 'warn_cd_multiple_people')
    op.drop_column('engine_settings', 'warn_cd_phone')
    op.drop_column('engine_settings', 'warn_cd_fake_presence')
    op.drop_column('engine_settings', 'warn_cd_face_hidden')
    op.drop_column('engine_settings', 'warn_cd_partial_face')
    op.drop_column('engine_settings', 'warn_cd_looking_side')
    op.drop_column('engine_settings', 'warn_cd_looking_up')
    op.drop_column('engine_settings', 'warn_cd_looking_down')
    op.drop_column('engine_settings', 'warn_cd_looking_away')
    op.drop_column('engine_settings', 'score_cd_speaker_audio')
    op.drop_column('engine_settings', 'score_cd_earbud')
    op.drop_column('engine_settings', 'score_cd_headphone')
    op.drop_column('engine_settings', 'score_cd_book')
    op.drop_column('engine_settings', 'score_cd_no_person')
    op.drop_column('engine_settings', 'score_cd_multiple_people')
    op.drop_column('engine_settings', 'score_cd_phone')
    op.drop_column('engine_settings', 'score_cd_fake_presence')
    op.drop_column('engine_settings', 'score_cd_face_hidden')
    op.drop_column('engine_settings', 'score_cd_partial_face')
    op.drop_column('engine_settings', 'score_cd_looking_side')
    op.drop_column('engine_settings', 'score_cd_looking_up')
    op.drop_column('engine_settings', 'score_cd_looking_down')
    op.drop_column('engine_settings', 'score_cd_looking_away')
    op.drop_column('engine_settings', 'speaker_repeat_interval')
    op.drop_column('engine_settings', 'speaker_occ2_repeat')
    op.drop_column('engine_settings', 'speaker_occ2_score')
    op.drop_column('engine_settings', 'speaker_occ2_warn_s')
    op.drop_column('engine_settings', 'speaker_occ1_repeat')
    op.drop_column('engine_settings', 'speaker_occ1_score')
    op.drop_column('engine_settings', 'speaker_occ1_warn_s')
    op.drop_column('engine_settings', 'speaker_alert_cooldown')
    op.drop_column('engine_settings', 'speaker_warn_cooldown')
    op.drop_column('engine_settings', 'face_hidden_score_2')
    op.drop_column('engine_settings', 'face_hidden_score_1')
    op.drop_column('engine_settings', 'partial_face_score')
    op.drop_column('engine_settings', 'fake_presence_dur_2')
    op.drop_column('engine_settings', 'fake_presence_dur_1')
    op.drop_column('engine_settings', 'no_person_dur_2')
    op.drop_column('engine_settings', 'no_person_dur_1')
    op.drop_column('engine_settings', 'face_hidden_dur_2')
    op.drop_column('engine_settings', 'face_hidden_dur_1')
    op.drop_column('engine_settings', 'partial_face_duration_gate')
    op.drop_column('engine_settings', 'detect_multiple_people')
    op.drop_column('engine_settings', 'detect_earbud')
    op.drop_column('engine_settings', 'detect_headphone')
    op.drop_column('engine_settings', 'detect_book')
    op.drop_column('engine_settings', 'detect_phone')
    op.drop_column('engine_settings', 'detect_speaker_audio')
    op.drop_column('engine_settings', 'detect_fake_presence')
    op.drop_column('engine_settings', 'detect_partial_face')
    op.drop_column('engine_settings', 'detect_face_hidden')
    op.drop_column('engine_settings', 'detect_looking_side')
    op.drop_column('engine_settings', 'detect_looking_up')
    op.drop_column('engine_settings', 'detect_looking_down')
    op.drop_column('engine_settings', 'detect_looking_away')
    op.add_column('engine_containers', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('engine_containers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
