"""bling_exam session

Revision ID: c9bc4a52c5db
Revises: 53ff521b7796
Create Date: 2026-02-11 14:35:03.314184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bc4a52c5db'
down_revision: Union[str, Sequence[str], None] = '53ff521b7796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('device_fingerprint', sa.String(), nullable=False))
    op.add_column('exam_sessions', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('exam_sessions', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column(
        'refresh_tokens',
        sa.Column('device_fingerprint', sa.String(), nullable=True)
    )

    # ---------------- BACKFILL ----------------
    op.execute("""
        UPDATE refresh_tokens
        SET device_fingerprint = 'legacy'
        WHERE device_fingerprint IS NULL
    """)

    # ---------------- ENFORCE NOT NULL ----------------
    op.alter_column(
        'refresh_tokens',
        'device_fingerprint',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'device_fingerprint')
    op.drop_column('exam_sessions', 'user_agent')
    op.drop_column('exam_sessions', 'ip_address')
    op.drop_column('exam_sessions', 'device_fingerprint')
    # ### end Alembic commands ###
