"""add pending to user_devices

Revision ID: e950e8e05fd5
Revises: c9bc4a52c5db
Create Date: 2026-02-11 15:29:36.361413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e950e8e05fd5'
down_revision: Union[str, Sequence[str], None] = 'c9bc4a52c5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_unlock_tokens')
    op.add_column('user_devices', sa.Column('pending', sa.Boolean(), server_default="true", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_devices', 'pending')
    op.create_table('account_unlock_tokens',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('account_unlock_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('account_unlock_tokens_pkey'))
    )
    # ### end Alembic commands ###
